version: "3.7"

services:
  
  synthetic-file-system:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: synthetic-file-system
    image: fuse_skeleton
    stdin_open: true
    tty: true
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    network_mode: "host"
