version: "3.3"

services:

  synthetic-file-system:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: synthetic-file-system
    image: fuse_skeleton
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - $XAUTHORITY:/root/.Xauthority
      - $MDH_HOME:/app/mdh/
    environment:
      - DISPLAY=$DISPLAY
    stdin_open: true
    tty: true
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    network_mode: "host"
    security_opt:
      - apparmor:unconfined
