name: Unittest and coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Test with pytest
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install pytest-cov
<<<<<<< HEAD
<<<<<<< HEAD
        python -m pytest tests/unit --cov=src
=======
        python -m pytest --cov=.
>>>>>>> 1255e9d9bd8f3cbf5195f0e00c0b560478181596
=======
        python -m pytest --cov=.
>>>>>>> 1255e9d9bd8f3cbf5195f0e00c0b560478181596
